[mypy]
python_version = 3.11
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = False
warn_no_return = False
check_untyped_defs = False

# Allow checking files in directories with hyphens
namespace_packages = True
explicit_package_bases = True
mypy_path = services
